### PR TITLE
added FloatProperty to set monochrome background color

### PR DESCRIPTION
**Pull request by jwendelmuth**

### CODE REVIEW

**Comment by lucasw** [comment]
Check out rviz ColorProperty.

**Comment by NikolasE** [comment]
I think this would provide a bit too much choice.

**Comment by lucasw** [comment]
What if the Global Options Background Color were used?
Is there a use case where the rviz camera would need a different background color than the standard rviz render window?

**Comment by NikolasE** [comment]
I personally like to have a black RVIZ background to work with, but it does not look good if the image is integrated into a document (thesis or bugreport).

**Comment by lucasw** [comment]
It seems like the default behavior should be that the rviz camera background is the same as the main rviz window.  If there is a need to have two different background colors at the same time, then there should be a full color property (and a checkbox to enable it, or can switching between them be handled otherwise?).

I like a color background to distinguish it from foreground objects that are frequently monochrome.

For future reference another useful capability would be to optionally have a transparent background in an rgba Image.

**Comment by lucasw** [comment]
Squashed and merged with c20d2bbc78212ee76e24f6174ad75e8173630966

**Comment by lucasw** [comment]
The background color doesn't match desired as revealed by #14 (channels are swapped), it will be corrected separate from this.

**Pull request closed without merging**
